#!/usr/bin/env bash

if [ $# -gt 0 ];then
    if [ "$1" == "npm" ]; then
        shift 1
        docker-compose run --rm \
            -w /var/www/html \
            node \
            npm "$@"
    elif [ "$1" == "knex" ]; then
        shift 1
        docker-compose run --rm \
            -w /var/www/html \
            node \
            knex "$@"
    else
        docker-compose "$@"
    fi
else
    docker-compose ps
fi
