#!/usr/bin/env bash

# Postgres credentials
export POSTGRES_USER=${POSTGRES_USER:-perk}
export POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
export POSTGRES_DB=${POSTGRES_DB:-myapp}

# Host ports
export POSTGRES_PORT=${POSTGRES_PORT:-5432}
export REDIS_PORT=${REDIS_PORT:-6379}


if [ $# -gt 0 ];then
    if [ "$1" == "init" ]; then
        cp docker/local.js config/local.js && \
        ./develop build && \
        ./develop npm install
    elif [ "$1" == "npm" ]; then
        shift 1
        docker-compose run --rm \
            -w /var/www/html \
            node \
            npm "$@"
    elif [ "$1" == "knex" ]; then
        shift 1
        docker-compose run --rm \
            -w /var/www/html \
            node \
            knex "$@"
    else
        docker-compose "$@"
    fi
else
    docker-compose ps
fi
