version: '2'
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: josecanhelp/perk/node
    volumes:
     - .:/var/www/html
    networks:
     - appnet
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    volumes:
     - pgdata:/var/lib/postgresql/data
    networks:
     - appnet
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - appnet
    ports:
      - 6379:6379
networks:
  appnet:
    driver: "bridge"
volumes:
  pgdata:
    driver: "local"
  redisdata:
    driver: "local"
